name: Deploy website to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::228041306689:role/github-actions-s3-deploy
          aws-region: ap-southeast-2

      - name: Deploy site to S3
        run: aws s3 sync ./ s3://shaunc-website --delete --exclude ".git/*" --exclude ".github/*" --exclude "README.md"

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E29DFBFZJ1TW0A --paths "/*"
